// packages/angular/demo/src/app.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { DsImageComponent, DsImageDirective, DsPictureComponent, DsPictureDirective } from '@desource/image-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [DsImageComponent, DsImageDirective, DsPictureComponent, DsPictureDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <main>
      <header>
        <span class="eyebrow">DeSource Image for Angular</span>
        <h1>Optimized images across four Angular surfaces.</h1>
        <p>DsImage and DsPicture components and directives share one provider and responsive-output model.</p>
      </header>

      <label class="control">
        Render width: <strong data-testid="width-value">{{ width() }}px</strong>
        <input
          data-testid="width"
          type="range"
          min="320"
          max="960"
          step="80"
          [value]="width()"
          (input)="width.set(+$any($event.target).value)"
        />
      </label>

      <section class="grid">
        <article>
          <span>DsImage component</span>
          <ds-image
            data-testid="image-component"
            src="/hero.jpg"
            alt="Aurora over a mountain lake"
            [width]="width()"
            [height]="540"
            sizes="sm:100vw md:50vw 680px"
            [quality]="82"
            [preload]="true"
            class="media"
          />
        </article>

        <article>
          <span>DsImage directive</span>
          <img
            data-testid="image-directive"
            dsImage="/hero.jpg"
            alt="Aurora reflected in water"
            [width]="width()"
            [height]="540"
            densities="1x 2x"
            class="media"
          />
        </article>

        <article>
          <span>DsPicture component</span>
          <ds-picture
            data-testid="picture-component"
            src="/hero.jpg"
            alt="Responsive mountain landscape"
            [width]="width()"
            [height]="540"
            [formats]="['avif', 'webp']"
            fallbackFormat="jpg"
            class="media"
          />
        </article>

        <article>
          <span>DsPicture directive</span>
          <picture
            data-testid="picture-directive"
            dsPicture="/hero.jpg"
            alt="Mountain landscape art direction"
            [width]="width()"
            [height]="540"
            [formats]="['webp']"
          >
            <img class="media" alt="Mountain landscape art direction" />
          </picture>
        </article>
      </section>
    </main>
  `
})
export class AppComponent {
  readonly width = signal(720);
}

// packages/svelte/demo/src/App.svelte
<script lang="ts">
  import { ipxProvider } from '@desource/image';
  import { DsImage, DsPicture, createDsImageBindings, setDsImageConfig } from '@desource/image-svelte';

  const config = setDsImageConfig({
    provider: 'ipx',
    providers: { ipx: ipxProvider() },
    screens: { sm: 640, md: 768, lg: 1024 }
  });
  const { dsImageAction, dsImageAttachment, dsPictureAction, dsPictureAttachment } = createDsImageBindings(config);
  let width = $state(720);
  let componentLoaded = $state(false);

  const actionOptions = $derived({
    src: '/hero.jpg',
    alt: 'Aurora reflected in a lake',
    width,
    height: 540,
    densities: '1x 2x',
    placeholder: true,
    placeholderClass: 'is-placeholder'
  });
</script>

<main>
  <header>
    <span class="eyebrow">DeSource Image for Svelte</span>
    <h1>One provider model for every Svelte surface.</h1>
    <p>Components, actions, and attachments generate the same responsive output without wrapper elements.</p>
  </header>

  <label class="control">
    Render width: <strong data-testid="width-value">{width}px</strong>
    <input data-testid="width" type="range" min="320" max="960" step="80" bind:value={width} />
  </label>

  <section class="grid">
    <article>
      <span>DsImage component</span>
      <DsImage
        data-testid="image-component"
        src="/hero.jpg"
        alt="Aurora above a mountain lake"
        {width}
        height={540}
        sizes="sm:100vw md:50vw 680px"
        quality={82}
        placeholder
        preload={{ fetchPriority: 'high' }}
        class="media"
        onload={() => (componentLoaded = true)}
      />
      <small data-testid="component-state">{componentLoaded ? 'decoded' : 'loading'}</small>
    </article>

    <article>
      <span>dsImageAction</span>
      <img
        data-testid="image-action"
        class="media"
        alt="Aurora reflected in a lake"
        use:dsImageAction={actionOptions}
      />
    </article>

    <article>
      <span>dsImageAttachment (Svelte 5.29+)</span>
      <img
        data-testid="image-attachment"
        class="media"
        alt="Mountain lake rendered by an attachment"
        {@attach dsImageAttachment({
          src: '/hero.jpg',
          alt: 'Mountain lake rendered by an attachment',
          width,
          height: 540,
          format: 'webp'
        })}
      />
    </article>

    <article>
      <span>DsPicture component</span>
      <DsPicture
        data-testid="picture-component"
        src="/hero.jpg"
        alt="Responsive mountain landscape"
        {width}
        height={540}
        formats={['avif', 'webp']}
        fallbackFormat="jpg"
        class="media-frame"
        imgAttrs={{ class: 'media' }}
      />
    </article>

    <article>
      <span>dsPictureAction</span>
      <picture
        data-testid="picture-action"
        class="media-frame"
        use:dsPictureAction={{
          src: '/hero.jpg',
          alt: 'Mountain landscape at dusk',
          width,
          height: 540,
          formats: ['webp'],
          fallbackFormat: 'jpg'
        }}
      >
        <img class="media" alt="Mountain landscape at dusk" />
      </picture>
    </article>

    <article>
      <span>dsPictureAttachment (Svelte 5.29+)</span>
      <picture
        data-testid="picture-attachment"
        class="media-frame"
        {@attach dsPictureAttachment({
          src: '/hero.jpg',
          alt: 'Mountain landscape rendered by an attachment',
          width,
          height: 540,
          formats: ['avif'],
          fallbackFormat: 'jpg'
        })}
      >
        <img class="media" alt="Mountain landscape rendered by an attachment" />
      </picture>
    </article>
  </section>
</main>
