// packages/react/src/lib/DsPicture.tsx
'use client';

import { forwardRef, useMemo } from 'react';
import type { DsNativeImageAttrs, DsPictureBindingOptions, DsPictureComponentProps } from './types.js';
import { useDsPictureProps } from './hooks.js';

export const DsPicture = forwardRef<HTMLPictureElement, DsPictureComponentProps>(function DsPicture(
  {
    src,
    alt,
    width,
    height,
    sizes,
    quality,
    format,
    formats,
    fallbackFormat,
    legacyFormat,
    fit,
    position,
    background,
    modifiers,
    provider,
    preset,
    densities,
    loading,
    decoding,
    fetchPriority,
    fetchpriority,
    priority = false,
    preload,
    placeholder,
    placeholderClass,
    imgAttrs,
    imgClassName,
    imgStyle,
    className,
    style,
    crossOrigin,
    crossorigin,
    nonce,
    onLoad,
    onError,
    referrerPolicy,
    referrerpolicy,
    useMap,
    usemap,
    isMap,
    ismap,
    children: _children,
    ...rest
  },
  ref
) {
  const options = useMemo<DsPictureBindingOptions>(() => {
    const nativeRecord = imgAttrs as Record<string, unknown> | undefined;
    return {
      src,
      alt,
      width,
      height,
      sizes,
      quality,
      format,
      formats,
      fallbackFormat,
      legacyFormat,
      fit,
      position,
      background,
      modifiers,
      provider,
      preset,
      densities,
      loading,
      decoding,
      fetchPriority,
      fetchpriority,
      priority,
      preload,
      placeholder,
      placeholderClass,
      pictureAttrs: rest,
      imgAttrs: {
        ...imgAttrs,
        referrerPolicy: referrerPolicy ?? imgAttrs?.referrerPolicy,
        referrerpolicy: referrerpolicy ?? nativeRecord?.['referrerpolicy'],
        useMap: useMap ?? imgAttrs?.useMap,
        usemap: usemap ?? nativeRecord?.['usemap'],
        isMap: isMap ?? (nativeRecord?.['isMap'] as boolean | undefined),
        ismap: ismap ?? nativeRecord?.['ismap']
      } as DsNativeImageAttrs,
      imgClassName,
      imgStyle,
      className,
      style,
      crossOrigin,
      crossorigin,
      nonce,
      onLoad,
      onError
    };
  }, [
    src,
    alt,
    width,
    height,
    sizes,
    quality,
    format,
    formats,
    fallbackFormat,
    legacyFormat,
    fit,
    position,
    background,
    modifiers,
    provider,
    preset,
    densities,
    loading,
    decoding,
    fetchPriority,
    fetchpriority,
    priority,
    preload,
    placeholder,
    placeholderClass,
    rest,
    imgAttrs,
    referrerPolicy,
    referrerpolicy,
    useMap,
    usemap,
    isMap,
    ismap,
    imgClassName,
    imgStyle,
    className,
    style,
    crossOrigin,
    crossorigin,
    nonce,
    onLoad,
    onError
  ]);
  const { pictureProps, sources, imgProps } = useDsPictureProps(options);

  return (
    <picture ref={ref} {...pictureProps}>
      {sources.map(({ key, ...source }) => (
        <source key={key} {...source} />
      ))}
      <img {...imgProps} alt={imgProps.alt} />
    </picture>
  );
});

// packages/svelte/src/lib/DsPicture.svelte
<script lang="ts">
  import { getImagePreloadLink, getPictureAttrs } from '@desource/image';
  import { normalizeCrossorigin } from '@desource/image/kit';
  import { getDsPictureProps, preloadImage, splitDsPictureAttributes, toDsImageInput } from './bindings.js';
  import { getDsImageConfig } from './context.js';
  import type { DsPictureBindingOptions, DsPictureComponentProps } from './types.js';

  let {
    src,
    alt,
    width,
    height,
    sizes,
    quality,
    format,
    formats,
    fallbackFormat,
    legacyFormat,
    fit,
    position,
    background,
    modifiers,
    provider,
    preset,
    densities,
    loading,
    decoding,
    fetchpriority,
    priority = false,
    preload,
    placeholder,
    placeholderClass,
    imgAttrs,
    class: className,
    style,
    crossorigin,
    nonce,
    onload,
    onerror,
    ...rest
  }: DsPictureComponentProps = $props();

  const config = getDsImageConfig();
  let loaded = $state(false);
  const distributed = $derived(splitDsPictureAttributes(rest));
  const bindingOptions = $derived<DsPictureBindingOptions>({
    src,
    alt,
    width,
    height,
    sizes,
    quality,
    format,
    formats,
    fallbackFormat,
    legacyFormat,
    fit,
    position,
    background,
    modifiers,
    provider,
    preset,
    densities,
    loading,
    decoding,
    fetchpriority,
    priority,
    preload,
    placeholder,
    placeholderClass,
    crossorigin,
    nonce,
    config,
    pictureAttrs: distributed.pictureAttrs,
    attrs: distributed.imgAttrs,
    imgAttrs,
    class: className,
    style,
    onload,
    onerror
  });
  const imageInput = $derived(toDsImageInput(bindingOptions));
  const picture = $derived(getPictureAttrs(imageInput, config));
  const elementProps = $derived(getDsPictureProps(bindingOptions, loaded));
  const basePreload = $derived(preload ? getImagePreloadLink(imageInput, config) : undefined);
  const preloadSource = $derived(picture.sources[0]);
  const nonceAttrs = $derived(nonce ? { nonce } : {});

  $effect(() => {
    const attrs = picture.img;
    const key = `${attrs.src}\n${attrs.srcset ?? ''}\n${attrs.sizes ?? ''}\n${attrs.placeholderSrc ?? ''}`;
    if (!key) return;
    loaded = false;
    if (!attrs.placeholderSrc) return;
    return preloadImage(
      attrs,
      {
        ready() {
          loaded = true;
        },
        error(event) {
          onerror?.(event);
        }
      },
      normalizeCrossorigin(crossorigin)
    );
  });

  function handleLoad(event: Event) {
    if (picture.img.placeholderSrc && !loaded) return;
    loaded = true;
    onload?.(event);
  }

  function handleError(event: Event) {
    onerror?.(event);
  }
</script>

<svelte:head>
  {#if basePreload}
    <link
      rel="preload"
      as="image"
      href={basePreload.href}
      imagesrcset={preloadSource?.srcset ?? basePreload.imagesrcset}
      imagesizes={preloadSource?.sizes ?? basePreload.imagesizes}
      fetchpriority={basePreload.fetchpriority}
      crossorigin={normalizeCrossorigin(crossorigin)}
      {...nonceAttrs}
    />
  {/if}
</svelte:head>

<picture {...elementProps.pictureAttrs} data-ds-picture="">
  {#each elementProps.sources as source (`${source.type}:${source.srcset}`)}
    <source type={source.type} srcset={source.srcset} sizes={source.sizes} data-ds-image-source="" />
  {/each}
  <img {...elementProps.imgAttrs} data-ds-picture-img="" onload={handleLoad} onerror={handleError} />
</picture>
